analyzer:
  plugins:
    - custom_lint
    # - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.graphql.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.mapper.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
    # - "test/**/*.dart"
    # - "test/*.dart"
    - "lib/generated/**/*.dart"
    - "lib/generated/*.dart"
    - "tools/**/*.dart"
    - "tools/*.dart"
    - "super_lint/**/*.dart"
    - "super_lint/*.dart"
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    unused_import: warning
    invalid_annotation_target: ignore

custom_lint:
  rules:
    - prefer_named_parameters:
      threshold: 2
      excludes:
        - "test/*.dart"
        - "test/**/*.dart"
        - "integration_test/*.dart"
        - "integration_test/**/*.dart"
    - incorrect_todo_comment:
    - prefer_is_empty_string:
    - prefer_is_not_empty_string:
    - avoid_unnecessary_async_function:
    - prefer_async_await:
    - prefer_lower_case_test_description:
      test_methods:
        - method_name: "test"
          param_name: "description"
        - method_name: "stateNotifierTest"
          param_name: "description"
        - method_name: "testWidgets"
          param_name: "description"
        - method_name: "testGoldens"
          param_name: "description"
    - avoid_hard_coded_colors:
      excludes:
        - "test/*.dart"
        - "test/**/*.dart"
        - "integration_test/*.dart"
        - "integration_test/**/*.dart"
    - test_folder_must_mirror_lib_folder:
      lib_folder_path: "lib"
      test_folder_paths:
        - "test/unit_test"
        - "test/widget_test"
    - avoid_hard_coded_strings:
      includes:
        - "lib/ui/component/**/*.dart"
        - "lib/ui/component/*.dart"
        - "lib/ui/page/**/*_page.dart"
        - "lib/ui/page/**/view_model/*.dart"
        - "lib/ui/page/**/*_dialog.dart"
    - incorrect_parent_class:
      excludes:
        - "lib/navigation/routes/app_router.dart"
        - "lib/ui/base/*.dart"
    - missing_expanded_or_flexible:
    - prefer_importing_index_file:
      excludes:
        - "test/*.dart"
        - "test/**/*.dart"
        - "integration_test/*.dart"
        - "integration_test/**/*.dart"

dart_code_metrics:
  metrics:
    # cyclomatic-complexity: 20
    maximum-nesting-level: 8
    #    number-of-parameters: 4
    # source-lines-of-code: 50
  rules:
    - always-remove-listener
    - no-boolean-literal-compare
    - no-magic-number:
      allowed: [-1, 0, 1, 2, 3]
    - no-equal-then-else
    - prefer-trailing-comma
    - double-literal-format
    - prefer-first
    - prefer-last
    - avoid-unnecessary-setstate
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - avoid-wrapping-in-padding
    - avoid-nested-conditional-expressions:
        acceptable-level: 3
        ignored-annotations:
          - allowedAnnotation
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-missing-enum-constant-in-map
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-type-assertions
    - prefer-async-await
    - prefer-correct-type-name:
        - min-length: 2
        - max-length: 100
    - prefer-iterable-of
    - avoid-expanded-as-spacer
    - avoid-shrink-wrap-in-lists
    - prefer-correct-edge-insets-constructor
    - use-setstate-synchronously
    - avoid-double-slash-imports

linter:
  rules:
    - always_declare_return_types
    # - always_put_control_body_on_new_line
    # - always_put_required_named_parameters_first
    # - always_require_non_null_named_parameters
    - annotate_overrides
    #    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_print
    #    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - prefer_void_to_null
    - void_checks
    - await_only_futures
    - cancel_subscriptions
    # - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - library_names
    - library_prefixes
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - null_closures
    # - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    # - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    # - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    # - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - sized_box_for_whitespace
    # - slash_for_doc_comments
    # - sort_child_properties_last
    - sort_pub_dependencies
    - throw_in_finally
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    # - use_key_in_widget_constructors
    # - use_rethrow_when_possible
    - valid_regexps
    - close_sinks
    - flutter_style_todos
    # - eol_at_end_of_file
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - non_constant_identifier_names
    - prefer_relative_imports
    - use_super_parameters
